### ISSUE TITLE
Incorporate scuttlebutt-guide into ssb-handbook?

### ISSUE THREAD

**Issue by stv0g** [ssbc/scuttlebutt-guide#3]
@mixmix @christianbundy 

Are you open to a pull request which would merge the content of this repo into [ssb-handbook](https://github.com/ssbc/scuttlebutt.nz)?

Or is there a reason for a dedicated repo?

**Comment by christianbundy** [comment]
I don't have any opinions on this, I might ping @mixmix on Scuttlebutt. I think his GitHub notifications are usually off.

**Comment by stv0g** [comment]
There seems to be no interest. I will close the issue then.
